### ISSUE TITLE
Markdown needs more attention

### ISSUE THREAD

**Issue by egeland** [mvila/npm-addict#1]
When there's markdown in the displayed output, it should probably be rendered or extracted.

Example from today:
![image](https://cloud.githubusercontent.com/assets/1281379/12692919/1e07b4f8-c742-11e5-8240-b889ade8c778.png)

Perhaps that image link should be ignored and a line of text found?

**Comment by mvila** [comment]
I am not sure about that. Markdown should not be present in the `description` property of `package.json` and it seems to be very rare.

**Comment by mvila** [comment]
Actually, when the description is missing from package.json, npm tries to generate one from the README. Unfortunately, the result is not great, I have tried to improve it by stripping the markdown tags. Let's see what it looks.

**Comment by mvila** [comment]
Apparently, the markdown down stripper is doing a good job so I think I can close this issue.
