### ISSUE TITLE
Provide RSS

### ISSUE THREAD

**Issue by busterc** [mvila/npm-addict#3]
It would be nice to have an RSS feed. I personally would use it with IFTTT to get daily emails. So, if you provided a daily and/or weekly newsletter that'd be easier for me; but I'd be happy with a simple RSS feed.

**Comment by SimonS** [comment]
:+1:

**Comment by mvila** [comment]
Thanks for your feedback. There will be an RSS feed very soon. :+1:

**Comment by mvila** [comment]
Here they are: https://npmaddict.com/#/feeds
