### ISSUE TITLE
Can’t load the site for several days now

### ISSUE THREAD

**Issue by moltar** [mvila/npm-addict#30]
Seems to attempt to load for a while only to fail in the end.

Accessing from Vietnam, but also tried Singapore VPN.

Thank you.

**Comment by mvila** [comment]
Thanks @moltar! The monitoring system I am using was not configured properly, so I didn't know the server was down. I restarted it, and it should work by now, but it might be a bit slow for a while because there is a lot of package updates to catch up.

**Comment by moltar** [comment]
Thank you dude
