### ISSUE TITLE
Got stack on SEPTEMBER 15TH

### ISSUE THREAD

**Issue by jgudan** [mvila/npm-addict#31]
The site is stuck on September 15th and does not load new content.

**Comment by mvila** [comment]
Thanks, @jgudan, for letting me know.

It seems related to this:

https://github.blog/changelog/2021-09-08-npm-couchdb-upgrade-will-reset-sequence-number/

I'll fix the issue ASAP.

**Comment by mvila** [comment]
I've reset the npm registry CouchDB sequence number, and npm addict should be able to sync with the npm registry again. 

Unfortunately, we've lost 5 days of npm package updates.
