### ISSUE TITLE
Is site down?

### ISSUE THREAD

**Issue by moltar** [mvila/npm-addict#32]
Getting nothing on the page.

**Comment by mvila** [comment]
The current server is overloaded and I'm afraid I'll have to upgrade to a bigger one. It may take a few hours. I'm very sorry about that.

**Comment by moltar** [comment]
Thanks, @mvila! Appreciate you work on this :)

**Comment by mvila** [comment]
The problem should be solved by now. Sorry @moltar, it took more time than I expected. Instead of upgrading the server, I spent time optimizing the code.

**Comment by moltar** [comment]
Thanks @mvila! :) I have already had a chance to get my fix last night hehe
