### ISSUE TITLE
Got stuck on Dec 29

### ISSUE THREAD

**Issue by moltar** [mvila/npm-addict#34]
![image](https://user-images.githubusercontent.com/491247/210321241-4296ef88-a22c-43e4-bc15-2e7feca29281.jpeg)

Happy new year! 🥳

**Comment by mvila** [comment]
Thank you, @moltar, for reporting the issue.

I just restarted the server (which was running for 244 days). Hopefully, everything should go back to normal. So now, the server is fetching new entries from the npm feed, but it will take time (maybe one or two days) to catch up with one week of updates.

Happy new year to you too! 🌟

**Comment by mvila** [comment]
Actually, it is not so bad.

Only 96,566 npm entries must be fetched and analyzed (with some GitHub API requests that can be delayed because of the request rate limit).

I thought it would be more, though.

I guess it is because of the holiday season! 😄

**Comment by moltar** [comment]
> I guess it is because of the holiday season!

Which can be hit or miss, devs love to write on xmas 😁 

Anyhow, thanks for fixing it. I will go & indulge then!
