### ISSUE TITLE
npm addict will be sunsetting on May 31st, 2023

### ISSUE THREAD

**Issue by mvila** [mvila/npm-addict#35]
It's been a great ride, but it's time to say goodbye. **npm addict** will be sunsetting on **May 31st, 2023**.

To learn more, please click on the following link:

https://npmaddict.com/#/sunset

**Comment by moltar** [comment]
Farewell!

I was here until the last day. This site will be missed. Used to be one of my favourite past times.

Thank you for all of your efforts in the creation and maintenance all these years!

**Comment by mvila** [comment]
Thank you very much @moltar! 😃
