### ISSUE TITLE
Site renders poorly on mobile

### ISSUE THREAD

**Issue by geirman** [mvila/npm-addict#4]
And this is as far left as I can view the contents. Can't drag any further right.

![screenshot_2016-02-07-04-51-31](https://cloud.githubusercontent.com/assets/1640318/12872430/e1800056-cd56-11e5-9182-f24f60888369.png)

**Comment by mvila** [comment]
Thanks @geirman for your feedback. What browser are you using?

**Comment by geirman** [comment]
![img_20160207_062934](https://cloud.githubusercontent.com/assets/1640318/12872887/44f088b0-cd64-11e5-9149-d0fb64286d36.jpg)

**Comment by mvila** [comment]
@geirman: Should be better now. :) Thanks again for your feedback, the mobile rendering was fine a few days ago but I broke it after a change. Could confirm that's okay for you now?

**Comment by geirman** [comment]
No worries! Looks much better now :)

**Comment by mvila** [comment]
Fantastic! Cheers man. :)
