### ISSUE TITLE
Possible support for daily/weekly emails?

### ISSUE THREAD

**Issue by amilajack** [mvila/npm-addict#5]
Love nom-addict so much! This would be an excellent addition.

**Comment by mvila** [comment]
Thanks for your suggestion but since there are [many existing solutions](https://www.google.com/#safe=off&q=rss+to+email) to transform [RSS feeds](https://npmaddict.com/#/feeds) to emails, this is something I will probably not implement.

**Comment by amilajack** [comment]
Never knew about that. Thanks!
