### ISSUE TITLE
The updates had stopped on April 20th

### ISSUE THREAD

**Issue by moltar** [mvila/npm-addict#9]
Hey Manuel, thanks for the site.

I used to check it every day. But now it is not updating anymore.

Thanks.

**Comment by mvila** [comment]
Hi @moltar,

I am so sorry about that, but I cannot fix the issue now. The problem is related to an issue in replicate.npmjs.com (https://npm.community/t/replicate-npmjs-com-sequence-id-reset/7046), and I am waiting for a response from npm support.

**Comment by moltar** [comment]
Ok, thanks for the update!

Hope it gets resolved soon and I can get my addiction back :)

**Comment by mvila** [comment]
No answer from npm support, so I reset fetching from the last entry.
